name: environment
channels:
  - defaults
  - conda-forge
dependencies:
  - boost>=1.53
  - breathe>=4.18.1
  - cython
  - eigen>=3.3.7
  - myst-parser
  - numpy
  - pytest
  - python>=3.7
  - sphinx>=3.0.4
  - sphinxcontrib-bibtex 
  - sphinx_rtd_theme>=0.4.3
  - pip
